---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Login private registry '{{  docker_private_registry_host }}'
    docker_login:
      registry: '{{ docker_private_registry_host }}'
      username: '{{ docker_private_registry_username }}'
      password: '{{ docker_private_registry_password }}'
      email: pi@workty.com

  - name: Find all running containers
    shell: docker ps | awk '{ print $0 }' | sed -n '2p' | grep -o "{{ docker_private_registry_imageprefixname }}-[^*]*" | awk '{ print $1 }'
    register: running_containers_names

  - name: Stop the running containers
    shell: docker stop {{ item }}
    with_items:
     - "{{ running_containers_names.stdout_lines }}"
    ignore_errors: True

  - name: Remove the containers
    shell: docker rm {{ item }}
    with_items:
     - "{{ running_containers_names.stdout_lines }}"
    ignore_errors: True

  - name: Run the new container '{{ docker_private_registry_imagename }}'
    docker:
      name: '{{ docker_private_registry_imageprefixname }}-{{ docker_private_registry_image_version }}'
      image: '{{  docker_private_registry_host }}/{{ docker_private_registry_username }}/{{ docker_private_registry_imagename }}'
      pull: always
      net: host
      state: reloaded
      restart_policy: always
      memory_limit: 0
      ports:
       - 3000:3000
       - 3001:3001
       - 3002:3002
       - 3003:3003
      volumes:
       /mnt/workty:/mnt/workty
      env:
         SERVICE_TAGS: ["{{ ansible_default_ipv4.address }}", '{{ docker_private_registry_image_version }}', "{{ ansible_lsb }}"]
         SERVICE_NAME: "{{ ansible_hostname }}-{{ ansible_machine }}-{{ docker_private_registry_branch_type }}-{{ docker_private_registry_image_version }}"